// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwkipmjfqjgxqunvsmbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3a2lwbWpmcWpneHF1bnZzbWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODMwMjUsImV4cCI6MjA3MTA1OTAyNX0.etAMF19puUYY6F-PASDg8PUlwZ77JbJxsJz-6Ry7cdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});